# Generated by Django 5.1.4 on 2025-02-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_mymodel_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
