# Generated by Django 5.1.4 on 2025-02-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='Django_project_1/image/', verbose_name='Изображение'),
        ),
    ]
